name: Build and Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build_arm:
    name: Build AmneziaWG for ARM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu libmnl-dev libnl-3-dev libnl-genl-3-dev
          
      - name: Clone amneziawg-go repository
        run: |
          git clone https://github.com/amnezia-vpn/amneziawg-go.git
          
      - name: Build amneziawg-go for ARM
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: arm
          GOARM: 7
          CC: arm-linux-gnueabihf-gcc
        run: |
          cd amneziawg-go
          go build -v -o amneziawg-go-arm
          
      - name: Upload ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-go-arm
          path: amneziawg-go/amneziawg-go-arm
  build_arm64:
    name: Build AmneziaWG for ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu libmnl-dev libnl-3-dev libnl-genl-3-dev
          
      - name: Clone amneziawg-go repository
        run: |
          git clone https://github.com/amnezia-vpn/amneziawg-go.git
          
      - name: Build amneziawg-go for ARM64
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
        run: |
          cd amneziawg-go
          go build -v -o amneziawg-go-arm64
          
      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-go-arm64
          path: amneziawg-go/amneziawg-go-arm64
